# Generated by Django 4.2.1 on 2023-06-02 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_serviceorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOSFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_orgid', models.CharField(blank=True, max_length=200, null=True)),
                ('repid', models.IntegerField(blank=True, null=True)),
                ('sodrid', models.IntegerField(blank=True, null=True)),
                ('topid', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='IOSfiles/')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('fileName', models.CharField(blank=True, max_length=150, null=True)),
                ('fileStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('fileComment', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, default='Others', max_length=100, null=True)),
                ('badge', models.CharField(max_length=400)),
                ('re_upload', models.CharField(blank=True, max_length=100, null=True)),
                ('download', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='static/thumb/')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'dent_iosfile',
                'managed': False,
            },
        ),
    ]
