# Generated by Django 4.2.1 on 2023-06-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_push_meta_data_pushed_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push_meta_data',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='push_meta_data',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
