# Generated by Django 4.2.1 on 2023-06-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_push_meta_data_age_alter_push_meta_data_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushed_file_data',
            name='orgid',
        ),
        migrations.AddField(
            model_name='pushed_file_data',
            name='pmd_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.push_meta_data'),
        ),
    ]
