# Generated by Django 4.2.1 on 2023-06-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_pushed_file_data_orgid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push_meta_data',
            name='orgid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organisation'),
        ),
    ]
